### ISSUE TITLE
Peer dependency missing at first run (Webpack)

### ISSUE THREAD

**Issue by meynety** [ablehq/firestore-explorer#4]
Hello,

I just followed from scratch the instructions from the Readme, I got this error when trying to run the app with `yarn serve` :

```
webapp]  ERROR  Error: A package is trying to access a peer dependency that should be provided by its direct ancestor but isn't
[webapp]                
[webapp] Required package: webpack (via "webpack/lib/RuleSet")
[webapp] Required by: vuetify-loader@virtual:9eb529c624fe063b94871f0dd358c1e5b6135b236dec6533becdde65861b53e47e25ea07cac5f9bbe02105fa8a4e67b70b8254fd00e8ffc5f855f02541d8bb56#npm:1.2.2 (via PATH_TO_PROJECT/firestore-explorer/explorer/.yarn/$$virtual/vuetify-loader-virtual-3cc4fb1248/0/cache/vuetify-loader-npm-1.2.2-e277a0d354-1.zip/node_modules/vuetify-loader/lib/)                      
[webapp]                
[webapp]  Require stack:
[webapp] - PATH_TO_PROJECT/firestore-explorer/explorer/.yarn/$$virtual/vuetify-loader-virtual-3cc4fb1248/0/cache/vuetify-loader-npm-1.2.2-e277a0d354-1.zip/node_modules/vuetify-loader/lib/plugin.js                                                         
[webapp] - PATH_TO_PROJECT/firestore-explorer/explorer/.yarn/cache/vue-cli-plugin-vuetify-npm-0.5.0-98c4393e12-1.zip/node_modules/vue-cli-plugin-vuetify/index.js                                                                                            
[webapp] - PATH_TO_PROJECT/firestore-explorer/explorer/.yarn/$$virtual/@vue-cli-service-virtual-887d6ff98f/0/cache/@vue-cli-service-npm-3.8.0-53f775b088-1.zip/node_modules/@vue/cli-service/lib/Service.js                                                  
[webapp] - PATH_TO_PROJECT/firestore-explorer/explorer/.yarn/$$virtual/@vue-cli-service-virtual-887d6ff98f/0/cache/@vue-cli-service-npm-3.8.0-53f775b088-1.zip/node_modules/@vue/cli-service/bin/vue-cli-service.js   
```    

I also tried to manually add `webpack` with both `yarn add webpack` and globally with `npm install -g webpack`, didn't work.
I have no experience with yarn, I'm sorry if maybe this is something trivial.

**Comment by madhu314** [comment]
What is the version of yarn you are using ?

If you are comfortable with npm, then you can replace yarn commands with the following

`yarn` ->  `npm install`
`yarn onetime_setup`-> `npm run onetime_setup`
`yarn serve` -> `npm run serve`

**Comment by sbres** [comment]
Hi,

I'm having the same issue.
My yarn version is this one :
```
yarn --version                                                                                                                            
2.0.0-rc.27
```

**Comment by madhu314** [comment]
Seems like issues with yarn2, can you use `yarn v1.21.1` ?

**Comment by sbres** [comment]
I will try.

For reference, and further debug:
Trying to debug this took me on a weird path, where I had to install some OSX headers.
I ended up having to update my osx version.
This bug could be related to the OSX version but I'm not really sure.

**Comment by sbres** [comment]
The setup worked when I used yarn v1.21.1

**Comment by madhu314** [comment]
@meynety can you use yarn version below 2 for this ? I will update the docs accordingly for future reference

**Comment by meynety** [comment]
Really sorry for the late answer, 

I do confirm that using yarn v1.22.0 fixes the issue, thanks a lot !

(For reference the issue is not OSX-related, I encountered it on Linux aswell (Manjaro v19.0.0) )
